### ISSUE TITLE
Conflict with 'Remove Reloading Screen' mod

### ISSUE THREAD

**Issue by slushieuwu** [PSJahn/blurredwindow#3]
https://modrinth.com/mod/rrls
![image](https://github.com/PSJahn/blurredwindow/assets/86991346/eb091428-1f2a-4b8d-a37d-5a9c7d57c6e3)

**Comment by blryface** [comment]
for me it seems it's probably because the rrls mod is doing something cursed to the UI which blurred window doesnt expect, I wonder which side should fix this

**Comment by PSJahn** [comment]
AFAIK this is due to the GLStateManger#clear call, which isn't called with an alpha value of zero which is why this results in the black background. Might be fixable by forcing the clear call to always use alpha 0 but i'd have to check if that would break anything else which I currently do not have the time for.

**Comment by dima-dencep** [comment]
My fix helps, however I'm not sure if it's correct for other mods, so it's disabled by default

**Comment by PSJahn** [comment]
> My fix helps, however I'm not sure if it's correct for other mods, so it's disabled by default

Thanks for your support! I'll mark this issue as closed.

**Comment by PSJahn** [comment]
> My fix helps, however I'm not sure if it's correct for other mods, so it's disabled by default

One last question though, would you be able to automatically enable this feature if the blurredwindow mod is loaded? (Could be done with a simple FabricLoader#isModLoaded check)

**Comment by dima-dencep** [comment]
no
